name: Deploy HTML to Red Hat VM

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Print full private key
      run: |
        printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}"

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts
        ls -l ~/.ssh
        head -n 5 ~/.ssh/id_rsa



    - name: Deploy HTML files via SCP
      run: |
        scp -r /home/kaushik/actions-runner/_work/demo-GithubAction/demo-GithubAction/* ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:${{ secrets.VM_DEST_DIR }}





